### ISSUE TITLE
Session start from JS is not supported in mobile app.  Error from Chromecast receiver

### ISSUE THREAD

**Issue by chrismillsnbcu** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#16]
I am adding Open Measurement to a Chromecast receiver Javascript app but keep getting this error when starting the session: `Session start from JS is not supported in mobile app.`  I went through the sample app a few times and I think everything is setup correctly, how do you determine if the sdk is being used in a mobile app?

**Comment by nlehrer** [comment]
I assume it is too late to help, but for future reference, that error indicates that you are using the "app" version of the OM SDK (e.g. `omsdk-v1.js`) rather than the Web version (`omweb-v1.js`). If the app is a Chromecast "Web Receiver app", it would use the OM SDK for Web: https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKJS/

That being said, connected TV devices including Chromecast are not officially supported yet. I'm closing the issue, but feel free to reopen with any further questions.
