### ISSUE TITLE
`<iframe srcdoc` conflict with Content-Security-Policy settings 

### ISSUE THREAD

**Issue by byunicorn** [InteractiveAdvertisingBureau/Open-Measurement-JSClients#37]
Hello,
We're trying to introduce omsdk on our website, and the sdk creates an iframe with `srcdoc` attribute, the value of `srcdoc` contains inline script, which conflicts with our website's Content Security Policy, makes the sdk fail to execute. 
(In order to avoid XSS attack, we set script-src to forbid inline script.)

Here is a simplest example to show the conflict.
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy" content="script-src 'self'">
</head>
<body>
  <iframe srcdoc="<p>hello</p><script>alert(1)</script>"></iframe>
</body>
</html>
```
The browser will console error:
![image](https://github.com/InteractiveAdvertisingBureau/Open-Measurement-JSClients/assets/2793450/3438f42e-7c39-4ffa-880b-30de2a830fbc)

So I wonder if it's possible to modify the inline script as 
```
<script type="text/template">
 window['omidVerificationProperties'] = { // blah blah };
</script>
``` 
then eval the content inside "text/template" in your external javascript. This could be a workaround for CSP.

Looking forward to your reply. Thanks in advance!

**Comment by nlehrer** [comment]
Hi, I understand the issue. 

I believe something like what you mentioned could work, but only for "full" access mode. See here for more info on access modes: https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKJS/accessmodes.html

For "limited" access mode, the iframe loading the verification script needs to be sandboxed, so we can't access the window from outside the frame. I think it is unlikely we will be able to solve this issue at least in the short term.

Are you planning to run all verification scripts in full access mode? This is less safe in other ways since verification scripts will have friendly access to the window that loaded OM SDK (typically the top window of the website).

There also may be another option, "domain" access mode. This uses `src` instead of `srcdoc` with an html file that you host on your website. More information [here](https://omsdk-demo-files.s3-us-west-2.amazonaws.com/docs/WebVideo/Publisher%2BQuick%2BStart%2BGuide.pdf) under "Publisher Support for Domain Access".

If you use domain access mode, you may be able to get this to work today, and it is more secure, but it is more work. For full access mode I would have to check with the OM working group about when we can prioritize this feature request.

**Comment by byunicorn** [comment]
Many thanks for the feedback, seems the "domain" access mode fits our requirement, we will look into it!
